---
title:               Zethus Suen
tagline:             UI/UX Designer.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Zethus Suen
twitter:             zethussuen
github:              zethussuen
email:               zethus.suen@gmail.com
google_analytics_id: UA-35067168-1
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
